## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
env:
  - DOCUMENTER_DEBUG=true

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
# matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PDFIO"); Pkg.test("PDFIO"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'import PDFIO; cd(joinpath(dirname(pathof(PDFIO)), "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push documentation from gh-pages
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PDFIO")); include(joinpath("docs", "make.jl"))'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
